OAUTH_HANDLED_PATHS = frozenset({
    '/.well-known/oauth-authorization-server',
    '/auth/oauth/authorize',
    '/auth/oauth/register',
    '/auth/oauth/callback',
    '/auth/oauth/token'
})

AUTHORIZATION_HEADER = 'Authorization'

TRANSPORT_SSE = 'sse'

VOLCENGINE_ACCESS_KEY = 'VOLCENGINE_ACCESS_KEY'
VOLCENGINE_SECRET_KEY = 'VOLCENGINE_SECRET_KEY'
VOLCENGINE_ACCESS_SESSION_TOKEN = 'VOLCENGINE_ACCESS_SESSION_TOKEN'
VOLCENGINE_ENDPOINT = 'VOLCENGINE_ENDPOINT'
VOLCENGINE_CREDENTIAL_TYPE = 'VOLCENGINE_CREDENTIAL_TYPE'

MCP_SERVER_MODE = 'MCP_SERVER_MODE'
MCP_SERVER_AUTH = 'MCP_SERVER_AUTH'
MCP_SERVER_PORT = 'MCP_SERVER_PORT'

CREDENTIAL_TYPE_ENV = 'env'
CREDENTIAL_TYPE_TOKEN = 'token'

AUTH_TYPE_OAUTH = 'oauth'
